import { GeneratedContent } from "@/hooks/use-photocard";

interface MemeCardProps {
  content: GeneratedContent;
}

export function MemeCard({ content }: MemeCardProps) {
  return (
    <div className="bg-black text-white p-8 rounded-none border-4 border-white shadow-2xl max-w-md w-full font-sans text-center relative overflow-hidden">
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/stardust.png')] opacity-20 pointer-events-none" />

      <h2 className="text-3xl font-black uppercase tracking-tighter leading-none mb-6 text-yellow-400 drop-shadow-[2px_2px_0_rgba(0,0,0,1)]">
        {content.post}
      </h2>

      <div className="space-y-4 relative z-10">
        {content.replies.map((reply, i) => (
          <div
            key={i}
            className="bg-white text-black p-3 transform rotate-1 hover:rotate-0 transition-transform duration-300 shadow-[4px_4px_0_rgba(0,0,0,1)] border-2 border-black"
          >
            <p className="font-bold text-sm uppercase mb-1 text-blue-600">
              {reply.username}:
            </p>
            <p className="font-medium text-lg leading-tight">"{reply.text}"</p>
          </div>
        ))}
      </div>

      <div className="mt-8 text-xs text-gray-500 uppercase tracking-widest">
        Generated by Clappic
      </div>
    </div>
  );
}
