import { Button } from "@/components/ui/button";
import { Download, Share2 } from "lucide-react";
import { toPng, toBlob } from "html-to-image";
import { toast } from "sonner";

interface DownloadActionsProps {
  targetRef: React.RefObject<HTMLDivElement | null>;
  fileName?: string;
}

export function DownloadActions({
  targetRef,
  fileName = "viral-card",
}: DownloadActionsProps) {
  const handleDownload = async () => {
    if (!targetRef.current) return;

    try {
      // Using html-to-image which supports modern CSS (lab/oklch) better
      const dataUrl = await toPng(targetRef.current, {
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: "transparent",
      });

      const link = document.createElement("a");
      link.download = `${fileName}.png`;
      link.href = dataUrl;
      link.click();

      toast.success("Image downloaded successfully!");
    } catch (error) {
      console.error("Download failed:", error);
      toast.error("Failed to download image.");
    }
  };

  const handleShare = async () => {
    if (!targetRef.current) return;

    try {
      const blob = await toBlob(targetRef.current, {
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: "transparent",
      });

      if (!blob) return;

      const file = new File([blob], `${fileName}.png`, { type: "image/png" });

      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: "Viral Photocard",
          text: "Check out this viral photocard generated by Clappic!",
        });
        toast.success("Shared successfully!");
      } else {
        await navigator.clipboard.write([
          new ClipboardItem({ "image/png": blob }),
        ]);
        toast.success("Image copied to clipboard!");
      }
    } catch (error) {
      console.error("Share failed:", error);
      toast.error("Failed to share image.");
    }
  };

  return (
    <div className="flex gap-4 mt-6">
      <Button
        onClick={handleDownload}
        className="w-full sm:w-auto gap-2"
        size="lg"
      >
        <Download className="w-4 h-4" />
        Download Image
      </Button>
      <Button
        variant="outline"
        onClick={handleShare}
        className="w-full sm:w-auto gap-2"
        size="lg"
      >
        <Share2 className="w-4 h-4" />
        Share / Copy
      </Button>
    </div>
  );
}
