import { Button } from "@/components/ui/button";
import { Download, Share2, Loader2 } from "lucide-react";
import { toPng, toBlob } from "html-to-image";
import { toast } from "sonner";
import { useState } from "react";

interface DownloadActionsProps {
  targetRef: React.RefObject<HTMLDivElement | null>;
  // Optional array of refs for multi-page batch download
  multiPageRefs?: React.MutableRefObject<HTMLDivElement | null>[];
  fileName?: string;
}

export function DownloadActions({
  targetRef,
  multiPageRefs,
  fileName = "viral-card",
}: DownloadActionsProps) {
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSharing, setIsSharing] = useState(false);

  const getTimestampedFilename = (index?: number) => {
    const now = new Date();
    const date = now.toISOString().split("T")[0];
    const time = now.toTimeString().split(" ")[0].replace(/:/g, "-");
    const suffix = index !== undefined ? `-page-${index}` : "";
    return `${fileName}${suffix}-${date}_${time}`;
  };

  const downloadSingleRef = async (element: HTMLElement, filename: string) => {
    const dataUrl = await toPng(element, {
      cacheBust: true,
      pixelRatio: 2,
      backgroundColor: "transparent",
    });

    const link = document.createElement("a");
    link.download = `${filename}.png`;
    link.href = dataUrl;
    link.click();
  };

  const handleDownload = async () => {
    setIsDownloading(true);

    try {
      if (multiPageRefs && multiPageRefs.length > 0) {
        // Batch download mode
        let downloadedCount = 0;

        for (let i = 0; i < multiPageRefs.length; i++) {
          const ref = multiPageRefs[i];
          if (ref.current) {
            await downloadSingleRef(ref.current, getTimestampedFilename(i));
            downloadedCount++;
            // Small delay to prevent browser throttling downloads
            if (i < multiPageRefs.length - 1) {
              await new Promise((resolve) => setTimeout(resolve, 500));
            }
          }
        }

        if (downloadedCount > 0) {
          toast.success(`Downloaded ${downloadedCount} images successfully!`);
        } else {
          throw new Error("No pages found to download");
        }
      } else if (targetRef.current) {
        // Single download mode
        await downloadSingleRef(targetRef.current, getTimestampedFilename());
        toast.success("Image downloaded successfully!");
      }
    } catch (error) {
      console.error("Download failed:", error);
      toast.error("Failed to download image.");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleShare = async () => {
    if (!targetRef.current) return;
    setIsSharing(true);

    try {
      const blob = await toBlob(targetRef.current, {
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: "transparent",
      });

      if (!blob) return;

      const file = new File([blob], `${getTimestampedFilename()}.png`, {
        type: "image/png",
      });

      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: "Viral Photocard",
          text: "Check out this viral photocard generated by Clappic!",
        });
        toast.success("Shared successfully!");
      } else {
        await navigator.clipboard.write([
          new ClipboardItem({ "image/png": blob }),
        ]);
        toast.success("Image copied to clipboard!");
      }
    } catch (error) {
      console.error("Share failed:", error);
      toast.error("Failed to share image.");
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <div className="flex gap-4 mt-6">
      <Button
        onClick={handleDownload}
        disabled={isDownloading || isSharing}
        className="w-full sm:w-auto gap-2"
        size="lg"
      >
        {isDownloading ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Download className="w-4 h-4" />
        )}
        {isDownloading ? "Downloading..." : "Download Image"}
      </Button>
      <Button
        variant="outline"
        onClick={handleShare}
        disabled={isDownloading || isSharing}
        className="w-full sm:w-auto gap-2"
        size="lg"
      >
        {isSharing ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Share2 className="w-4 h-4" />
        )}
        {isSharing ? "Sharing..." : "Share / Copy"}
      </Button>
    </div>
  );
}
