import { Button } from "@/components/ui/button";
import { Download, Share2, Loader2 } from "lucide-react";
import { toPng, toBlob } from "html-to-image";
import { toast } from "sonner";
import { useState } from "react";

interface DownloadActionsProps {
  targetRef: React.RefObject<HTMLDivElement | null>;
  fileName?: string;
}

export function DownloadActions({
  targetRef,
  fileName = "viral-card",
}: DownloadActionsProps) {
  const [isDownloading, setIsDownloading] = useState(false);
  const [isSharing, setIsSharing] = useState(false);

  const getTimestampedFilename = () => {
    const now = new Date();
    const date = now.toISOString().split("T")[0];
    const time = now.toTimeString().split(" ")[0].replace(/:/g, "-");
    return `${fileName}-${date}_${time}`;
  };

  const handleDownload = async () => {
    if (!targetRef.current) return;
    setIsDownloading(true);

    try {
      // Using html-to-image which supports modern CSS (lab/oklch) better
      const dataUrl = await toPng(targetRef.current, {
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: "transparent",
      });

      const link = document.createElement("a");
      link.download = `${getTimestampedFilename()}.png`;
      link.href = dataUrl;
      link.click();

      toast.success("Image downloaded successfully!");
    } catch (error) {
      console.error("Download failed:", error);
      toast.error("Failed to download image.");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleShare = async () => {
    if (!targetRef.current) return;
    setIsSharing(true);

    try {
      const blob = await toBlob(targetRef.current, {
        cacheBust: true,
        pixelRatio: 2,
        backgroundColor: "transparent",
      });

      if (!blob) return;

      const file = new File([blob], `${getTimestampedFilename()}.png`, {
        type: "image/png",
      });

      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: "Viral Photocard",
          text: "Check out this viral photocard generated by Clappic!",
        });
        toast.success("Shared successfully!");
      } else {
        await navigator.clipboard.write([
          new ClipboardItem({ "image/png": blob }),
        ]);
        toast.success("Image copied to clipboard!");
      }
    } catch (error) {
      console.error("Share failed:", error);
      toast.error("Failed to share image.");
    } finally {
      setIsSharing(false);
    }
  };

  return (
    <div className="flex gap-4 mt-6">
      <Button
        onClick={handleDownload}
        disabled={isDownloading || isSharing}
        className="w-full sm:w-auto gap-2"
        size="lg"
      >
        {isDownloading ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Download className="w-4 h-4" />
        )}
        {isDownloading ? "Downloading..." : "Download Image"}
      </Button>
      <Button
        variant="outline"
        onClick={handleShare}
        disabled={isDownloading || isSharing}
        className="w-full sm:w-auto gap-2"
        size="lg"
      >
        {isSharing ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Share2 className="w-4 h-4" />
        )}
        {isSharing ? "Sharing..." : "Share / Copy"}
      </Button>
    </div>
  );
}
