import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Sparkles, Loader2 } from "lucide-react";

interface InputSectionProps {
  jsonInput: string;
  setJsonInput: (value: string) => void;
  onRender: () => void;
  isLoading: boolean;
}

export function InputSection({
  jsonInput,
  setJsonInput,
  onRender,
  isLoading,
}: InputSectionProps) {
  return (
    <div className="space-y-6 bg-card/50 backdrop-blur-sm p-6 rounded-xl border border-border/50 shadow-sm">
      <div className="space-y-2">
        <Label htmlFor="json-input" className="text-lg font-semibold">
          Paste JSON Here
        </Label>
        <p className="text-xs text-muted-foreground">
          Paste the JSON generated by ChatGPT, Gemini, or Claude.
        </p>
      </div>

      <Textarea
        id="json-input"
        placeholder='{
  "post": "Your viral post text...",
  "replies": [
    { "username": "@user1", "handle": "user1", "text": "Reply 1" }
  ]
}'
        value={jsonInput}
        onChange={(e) => setJsonInput(e.target.value)}
        className="min-h-[300px] font-mono text-sm"
      />

      <Button
        onClick={onRender}
        disabled={isLoading || !jsonInput.trim()}
        className="w-full h-12 text-lg font-bold bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 transition-all shadow-lg hover:shadow-xl hover:scale-[1.02]"
      >
        {isLoading ? (
          <>
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
            Rendering...
          </>
        ) : (
          <>
            <Sparkles className="mr-2 h-5 w-5" />
            Render Photocard
          </>
        )}
      </Button>
    </div>
  );
}
